apiVersion: v1
kind: LimitRange
metadata:
  name: limits-prod
  namespace: ns-prod
spec:
  limits:
  - type: Container
    default:
      cpu: 400m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 256Mi
    max:
      cpu: 400m
      memory: 512Mi
